### ISSUE TITLE
Pretty-printers tests don't work on Windows CI since Rust 1.59

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#8843]
## Problem description
Pretty-printers tests don't work on Windows CI since Rust 1.59 (more precisely `nightly-2021-12-26`). See https://github.com/intellij-rust/intellij-rust/pull/8486.

Example from the [logs](https://github.com/intellij-rust/intellij-rust/runs/6004096151?check_suite_focus=true#step:22:57):
```
breakpoint set --file '\\?\D:\a\intellij-rust\intellij-rust\pretty_printers_tests\tests\nonzero.rs' --line 27
Breakpoint 1: no locations (pending). WARNING: Unable to resolve breakpoint to any actual locations. 
run
Process 4744 exited with status = 0 (0x00000000)
Process 4744 launched: 'D:\a\intellij-rust\intellij-rust\pretty_printers_tests\testbinary' (x86_64) 
print a
Error: use of undeclared identifier 'a'
print b
Error: use of undeclared identifier 'b'
```

## Steps to reproduce

Unable to reproduce it on a local Windows machine at the moment.

**Comment by Undin** [comment]
All pretty printer tests work on CI now, so let's close it
