### PR TITLE
Don't use ThreadTracker in production code

### PR DESCRIPTION
**Pull request by vlad20012**
Fixes NoClassDefFoundError.
The bug was introduced in #8746

### CODE REVIEW

File: src/test/kotlin/org/rust/lang/core/resolve2/ResolveCommonThreadPoolImpl.kt [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+ * found in the LICENSE file.
+ */
+
+package org.rust.lang.core.resolve2
+
+import com.intellij.testFramework.ThreadTracker
+import java.util.concurrent.ExecutorService
+import java.util.concurrent.ForkJoinPool
+
+class TestResolveCommonThreadPoolImpl : ResolveCommonThreadPool() {
```
Comment (Undin) [inline src/test/kotlin/org/rust/lang/core/resolve2/ResolveCommonThreadPoolImpl.kt:12]: Unfortunately, if service test implementations are located in test source sets of plugin A, plugin B depends on plugin A and you run tests in plugin B, you will get error because test code is not present in final zip of plugin A.
For example, EduTools plugin depends on Rust plugin.
So let's move it to main source set as we do with all other service test implementations

File: src/main/resources/META-INF/rust-core.xml [hunk 2]
```diff
@@ -1149,6 +1149,10 @@
         <filetype.prebuiltStubsProvider filetype="Rust"
                                         implementationClass="org.rust.lang.core.macros.MacroExpansionStubsProvider"/>
 
+        <applicationService serviceInterface="org.rust.lang.core.resolve2.ResolveCommonThreadPool"
+                            serviceImplementation="org.rust.lang.core.resolve2.ResolveCommonThreadPoolImpl"
+                            testServiceImplementation="org.rust.lang.core.resolve2.TestResolveCommonThreadPoolImpl"/>
```
Comment (Undin) [inline src/main/resources/META-INF/rust-core.xml:1154]: @vlad20012 maybe it's better to have a single implementation of thread pool creation in this case just to make sure that everything is fine in production as well
The corresponding error can be solved via:
- single service implementation and doing test code only things under `isUnitTestMode`
- still create test service implementation. But in addition, always set custom name for all created threads (I think it may be useful in general to understand what thread  does looking at thread dump, for example), and call `ThreadTracker.longRunningThreadCreated` in constructor of test service - it will be trivial since thread prefix will be custom
