### ISSUE TITLE
Extract enum variant refactoring should respect parent enum attributes

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#5283]
## Environment

* **IntelliJ Rust plugin version:** 0.2.122.3056-201-nightly
* **Rust toolchain version:** 1.42.0 (b8cedc004 2020-03-09) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.1 Ultimate Edition (IU-201.6668.121)
* **Operating system:** macOS 10.13.6

## Problem description
`Extract enum variant` refactoring introduced in #5037 and #5182 may produce invalid code when parent enum has attributes. For example, if enum has `#[derive(Debug)]`, extracted struct should have it too. Otherwise, it produces compiler error.

Looks like it's quite hard to support custom attributes because they can have arbitrary semantics, but it would be great to make this refactoring work with compiler attributes like `derive`

## Steps to reproduce
Before:
```rust
#[derive(Debug)]
enum IpAddr {
    V4/*caret*/(u8, u8, u8, u8),
    V6(String),
}

fn main() {
    let home = IpAddr::V4(127, 0, 0, 1);
    let loopback = IpAddr::V6(String::from("::1"));
    println!("{:?} {:?}", home, loopback)
}

```

After:
```rust
struct V4(pub u8, pub u8, pub u8, pub u8);

#[derive(Debug)]
enum IpAddr {
    V4(V4), // error[E0277]: `V4` doesn't implement `std::fmt::Debug`
    V6(String),
}

fn main() {
    let home = IpAddr::V4(V4(127, 0, 0, 1));
    let loopback = IpAddr::V6(String::from("::1"));
    println!("{:?} {:?}", home, loopback)
}
```

**Comment by Undin** [comment]
CC @mchernyavsky @Kobzol

**Comment by Kobzol** [comment]
I agree that copying `derive` would be very useful for this intention. Maybe also things like `repr(C)` could be copied? I see that the intfrastructure for querying attribute is in place, so it shouldn't be hard. Should I do it @mchernyavsky ?

**Comment by Undin** [comment]
@Kobzol We may convert this issue into meta issue, collect all possible stdlib attributes that can be affected by the refactoring and support them one by one. From my point of view, `derive` should be supported first as the most frequent attribute

**Comment by Kobzol** [comment]
Probably should wait for https://github.com/intellij-rust/intellij-rust/pull/5291 to be merged. I'll then try to work on it.
