### ISSUE TITLE
Pretty printers tests don't work with 2022.1 EAP binaries

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#8482]
Pretty printers tests fail with
```
Error while running LLDB:
Traceback (most recent call last):
  File "./lldb_batchmode.py", line 192, in <module>
    debugger = lldb.SBDebugger.Create()
AttributeError: module 'lldb' has no attribute 'SBDebugger'
```

For example, see https://github.com/intellij-rust/intellij-rust/runs/4978091150?check_suite_focus=true
