### ISSUE TITLE
Coverage does not compile in some projects

### ISSUE THREAD

**Issue by ta32** [intellij-rust/intellij-rust#8035]
Running tests with coverage does not compile in some projects

## Environment

* **IntelliJ Rust plugin version:** 0.4.158.4203-212
* **Rust toolchain version:** 1.56.0 (09c42c458 2021-10-18) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.2.3 (CL-212.5457.51)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Tests do not compile with grcov 0.8.2 for several projects but not others

## Steps to reproduce
coverage does not compile with https://github.com/ta32/issues/tree/master/rust_requests
coverage does not compile with https://github.com/ta32/issues/tree/master/clion_rocket

I also installed the nightly toolchain and this component
rustup toolchain install nightly-x86_64-pc-windows-msvc -component llvm-tools-preview
when I follow these instructions on windows after switching to nightly

https://github.com/mozilla/grcov#example-how-to-generate-source-based-coverage-for-a-rust-project

cargo build

```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names "\"-Zinstrument-coverage\"" --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
  --- stderr
  error: multiple input filenames provided (first two filenames are `-` and `"-Zinstrument-coverage"`)
```
I am not sure how clion compiles with gcrov and I don't get the same error message
I am using grcov 0.8.2

The first project compiles with the error:
error[E0463]: can't find crate for `pin_project_internal`

when I run tests with coverage
