### ISSUE TITLE
Fails to evaluate `anyhow` crate's build script after sync.

### ISSUE THREAD

**Issue by ledyba** [intellij-rust/intellij-rust#9959]
## Environment

* **IntelliJ Rust plugin version:** 0.4.185.5086-223
* **Rust toolchain version:** 1.66.1 (90743e729 2023-01-10) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.3.1 (CL-223.8214.51)
* **Operating system:** Windows 10 10.0
* **Macro expansion:** enabled

## Problem description

Failed to build project with this message:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> C:\Users\kaede\scoop\persist\rustup-msvc\.cargo\registry\src\github.com-1ecc6299db9ec823\anyhow-1.0.68\src\lib.rs:214:32
    |
214 | #![cfg_attr(backtrace, feature(error_generic_member_access, provide_any))]
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

![image](https://user-images.githubusercontent.com/391964/211981804-ef865f4d-868b-4fce-ab3e-2be42c2128e7.png)

## Steps to reproduce

1. Create a new project.
2. Add `anyhow = "1.0.68"` to dependencies. Do not push build button yet.
3. Push sync button.
4. Build the project.

After step 4, `cargo build` always fails. For workaround, remove /target/ and type `cargo build` from a terminal.

Maybe https://github.com/rust-lang/rust-analyzer/issues/12973, https://github.com/dtolnay/anyhow/issues/250 and https://github.com/dtolnay/anyhow/issues/288 are related issue.

https://github.com/intellij-rust/intellij-rust/issues/9198 may be not fully resolved or en-bugged.

**Comment by ledyba** [comment]
Maybe [The no-op always-success RUSTC_WRAPPER breaks build scripts · Issue #12973 · rust-lang/rust-analyzer](https://github.com/rust-lang/rust-analyzer/issues/12973) and [Rust analiser keeps prompting errors when upgrade to 1.65 stable toolchain · Issue #288 · dtolnay/anyhow](https://github.com/dtolnay/anyhow/issues/288) are related issue.

**Comment by mati865** [comment]
Possibly fixed by https://github.com/intellij-rust/intellij-rust/pull/9901

**Comment by Undin** [comment]
Fixed by #9901
