### ISSUE TITLE
Pretty printer tests don't work with 2023.1 builds

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#10009]
```
Error while running LLDB:
Traceback (most recent call last):
  File "/home/runner/work/intellij-rust/intellij-rust/pretty_printers_tests/./lldb_batchmode.py", line 197, in <module>
    debugger = lldb.SBDebugger.Create()
AttributeError: module 'lldb' has no attribute 'SBDebugger'
```
