### PR TITLE
Update Gradle IntelliJ plugin

### PR DESCRIPTION
**Pull request by Turbo87**
... and remove redundant plugin application

### CODE REVIEW

**Comment by matklad** [comment]
build have failed. May be it was not so redundant? ;)

**Comment by Turbo87** [comment]
hmm, that's strange. works perfectly at my other plugin...

**Comment by Turbo87** [comment]
this is actually related to the version update. looks like `0.0.34` is not compatible to Java 8:

```
Caused by: java.lang.NoClassDefFoundError: java/util/HashMap$Entry
```

works fine with `0.0.33`

**Comment by matklad** [comment]
I wonder why plugin application is included in the documentation: https://github.com/JetBrains/gradle-intellij-plugin#buildgradle.

**Comment by Turbo87** [comment]
because https://github.com/JetBrains/gradle-intellij-plugin/pull/49 isn't merged yet :wink:

**Comment by Turbo87** [comment]
if you use the old way before Gradle v2.1 for will need to apply them by hand (see [here](https://github.com/JetBrains/gradle-intellij-plugin#gradle--21-1)), but if you use the new plugin mechanism the plugins are automatically applied.

**Comment by matklad** [comment]
Hm, seems like we should use `plugin {}`  stuff for java and kotlin plugins as well

**Comment by Turbo87** [comment]
java is a builtin plugin so you only need to apply it without the dependency. Kotlin is not published on the gradle plugin repo AFAIK, so we can't do that.
