### PR TITLE
T: Enable pretty-printers tests on 2022.2

### LINKED ISSUE #8482: Pretty printers tests don't work with 2022.1 EAP binaries
Pretty printers tests fail with
```
Error while running LLDB:
Traceback (most recent call last):
  File "./lldb_batchmode.py", line 192, in <module>
    debugger = lldb.SBDebugger.Create()
AttributeError: module 'lldb' has no attribute 'SBDebugger'
```

For example, see https://github.com/intellij-rust/intellij-rust/runs/4978091150?check_suite_focus=true

### PR DESCRIPTION
**Pull request by ortem**
The tests were temporarily disabled due to the problem with certain 2022.2 EAP builds.
Fixes #8482

### CODE REVIEW

**Review by Undin — COMMENTED** [review]
I've updated 222 dependencies in master to the latest EAP, so I think we can finish this PR now

**Review by Undin — APPROVED** [review]
Thank you!
bors r+
